### ISSUE TITLE
[Architecture] Backbone (Swin Transformer)

### ISSUE THREAD

**Issue by IbrahimSaeedPurdue** [PurdueDualityLab/tf-maskformer#10]
- [ ] Verify shape of 3rd party tf swin transformer with the pytorch version
- [ ] Reorganize and Integrate 3rd party tf Swin Transformer over to our repo (Big tasks will be broken down after more analysis).
- [ ] We might need to write tests for the components that are used but not in the tf-models.

Existing trusted 3rd party implementation (not in TF-models):
https://github.com/sayakpaul/swin-transformers-tf

**Comment by Vishal-S-P** [comment]
This task is no more valid. Please delete.
