### ISSUE TITLE
[Data Pipeline] Panoptic Segmentation code in TFMG

### ISSUE THREAD

**Issue by RomanczuG** [PurdueDualityLab/tf-maskformer#22]
Example of COCO panoptic dataset in TensorFlow -
- https://github.com/google-research/deeplab2/blob/main/g3doc/setup/coco.md
- https://github.com/tensorflow/models/blob/panoptic-segmentation/official/vision/beta/projects/panoptic_maskrcnn/dataloaders/panoptic_maskrcnn_input.py

**Comment by TaewoooK** [comment]
https://taewooeddie.notion.site/Panoptic_maskrcnn_input-67372a9c9e9d444aa8b27ac290f0beb9

**Comment by TaewoooK** [comment]
Can complete after the other Data Pipeline stories are complete
