### ISSUE TITLE
[Debug] Integrate code from all the subteams

### ISSUE THREAD

**Issue by Vishal-S-P** [PurdueDualityLab/tf-maskformer#24]
- [ ] Verify all the unit tests are done and each subteam is able to match the output from pytorch codebase
- [ ] Add main.py and reorganize the code if necessary
- [ ] Ask respective team members to redo the code if it does not follow TFMG guidelines 
- [ ] Resolve all the bugs and close all the development issues on github projects

**Comment by Wenxin-Jiang** [comment]
- [ ] Integrating data pipeline
- [ ] Integrating configs
- [ ] Integrating modeling
- [ ] Integrating training metrics
- [ ] Integrating matcher
- [ ] End-to-end test
